<a href="https://colab.research.google.com/github/jaesgithub/ECON-323/blob/main/January_27th.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
class Person:
  def __init__(self, name, age):
    self.name = name
    self.age = age

In [2]:
p = Person("Jae", 21)
print(p.name)
print(p.age)

Jae
21


In [3]:
def mean(numbers):
  return sum(numbers) / len(numbers)

print(mean([1, 2, 3]))

2.0


In [4]:
print(mean([4, 2, 3, 10]))

4.75


In [5]:
class BankAccount:
  def __init__(self, balance):
    self.balance = balance # attribute (data)

  def deposit(self, amount):
    self.balance += amount # method (function) uses the data

# Create an object (instance) of BankAccount
account_1 = BankAccount(100) # 'account' is the object, starting balance = 100
account_2 = BankAccount(200)

# Call the deposit method on the object to update balance
account_1.deposit(50)
account_2.deposit(30)

# Check the updated balance
print(account_1.balance) # Output: 150
print(account_2.balance) # Output: 230

150
230


In [6]:
import numpy as np

In [7]:
x_id = np.array([1, 2, 3])
print(x_id)

[1 2 3]


In [8]:
type(x_id)

numpy.ndarray

In [9]:
print(x_id[0])
print(x_id[0:2])

1
[1 2]


In [10]:
print(x_id[0:3] == x_id[:])
print(x_id[0:2])

[ True  True  True]
[1 2]


In [11]:
x_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(x_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
print(x_2d[1, 2]) # Indexing into two dimensions!

6


In [13]:
print(x_2d[0, 0]) # Indexing into two dimensions!

1


In [14]:
print(x_2d[0, :]) # [row, column]
print(x_2d[1, :])

[1 2 3]
[4 5 6]


In [15]:
print(x_2d[:, 0])
print(x_2d[:, 1])

[1 4 7]
[2 5 8]


In [16]:
x_3d_list = [[[1, 2, 3], [4, 5, 6]], [[10, 20, 30], [40, 50, 60]]]
x_3d = np.array(x_3d_list)
print(x_3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[10 20 30]
  [40 50 60]]]


In [17]:
print(x_3d[0])
print()
print(x_3d[1])

[[1 2 3]
 [4 5 6]]

[[10 20 30]
 [40 50 60]]


In [18]:
print(x_3d[0, :, :])

[[1 2 3]
 [4 5 6]]


In [19]:
print(x_3d[1, :, :])

[[10 20 30]
 [40 50 60]]


In [20]:
print(x_3d[1, 0, :])

[10 20 30]


In [21]:
print(x_3d[1, 0, 2])

30


A 3D array is a data structure that stores elements in three dimensions—depth (or layers), rows, and columns—essentially forming a cube of data. It can be visualized as a collection of multiple 2D arrays stacked together, similar to stacking multiple trays on top of each other.

An element in a 3D array arr is accessed using the notation arr[i][j][k], where i is the depth, j is the row, and k is the column.

A 3D array can be declared by specifying all three dimensions.

For example:
int arr[4][5][8] declares a 3D integer array with 4 layers, 5 rows per layer, and 8 columns per row
This array can store a total of 4 × 5 × 8 = 160 elements