<a href="https://colab.research.google.com/github/jaesgithub/ECON-323/blob/main/January_29th.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
# 1D Array
x = np.array([1, 2, 3, 4])
print(x.shape) # 4 elements, 1 dimension
print(x.dtype)

(4,)
int64


In [ ]:
x = np.array([True, False, True])
print(x.shape)
print(x.dtype)

(3,)
bool


In [ ]:
x = np.array([[1, 2, 3], [4, 5, 6]])
print(x.shape) # 2 rows and 3 columns
print(x.dtype)

(2, 3)
int64


In [5]:
rows, columns = x.shape

In [6]:
sizes = (2, 3, 4)
x = np.zeros(sizes) # Note, a tuple!
x

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [7]:
y = np.ones(4) # 4 elements
y

array([1., 1., 1., 1.])

In [8]:
np.ones((4, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
print("2 + x = ", 2 + x)

2 + x =  [[[2. 2. 2. 2.]
  [2. 2. 2. 2.]
  [2. 2. 2. 2.]]

 [[2. 2. 2. 2.]
  [2. 2. 2. 2.]
  [2. 2. 2. 2.]]]


In [10]:
x = np.linspace(0, 25, 10)
x

array([ 0.        ,  2.77777778,  5.55555556,  8.33333333, 11.11111111,
       13.88888889, 16.66666667, 19.44444444, 22.22222222, 25.        ])

In [11]:
np.mean(x)

np.float64(12.5)

In [12]:
np.std(x)

np.float64(7.9785592313028175)

In [13]:
np.max(x)

np.float64(25.0)

In [16]:
np.random.seed(1237)
x = np.random.rand(10) # Generates 10 random floats 0 <= number < 1
print(x)

[0.7272802  0.72065558 0.76229658 0.05594622 0.08879156 0.14308458
 0.32747265 0.23884426 0.45610357 0.01783743]


In [19]:
def f(val):
  if val < 0.3:
    return "low"
  else:
    return "high"

print(f(0.1)) # Scalar, no problem
print(f(0.5))

# f(x) # array, fails since f() is scalar, not vector

# f_vec = np.vectorize(f) # Creates a vectorized version of f().
# print(f_vec(x))

low
high
